name: Bug Fix
description: Corriger un bug
labels: ["type:fix", "priority:high"]
body:
  - type: textarea
    id: bug
    attributes:
      label: 🐞 Description du bug
      description: Décris précisément le bug à corriger
      placeholder: |
        Exemple : le bouton "Ajouter" ne fonctionne pas sur /dashboard
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Étapes pour reproduire le bug
      description: Décris pas à pas comment reproduire le bug
      placeholder: |
        1. Aller sur la page ...
        2. Cliquer sur ...
        3. Observer le bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Résultat attendu
      description: Comment le système devrait se comporter normalement
      placeholder: |
        - Le bouton fonctionne
        - Aucune erreur dans la console
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 📝 Checklist avant dev
      description: Vérifications et bonnes pratiques à faire avant de coder
      placeholder: |
        - Vérifier le lint et corriger les erreurs éventuelles
        - Vérifier que le build compile
        - Identifier tous les composants affectés
        - Ajouter ou mettre à jour les tests unitaires si nécessaire
        - Ajouter des commentaires pour toute question ou ambiguïté avant de commencer
        - Vérifier que les tests existants passent après correction
        - Créer une branche dédiée pour le bugfix
        - Pusher les changements sur Git
        - Ouvrir une Pull Request vers la branche principale
    validations:
      required: true
